# build.ps1 - 生成 assets-data.js 与单文件版 index-standalone.html
# 用法: powershell -ExecutionPolicy Bypass -File .\build.ps1
$ErrorActionPreference = "Stop"
$root = $PSScriptRoot

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("/* auto-generated by build.ps1 - 请勿手改;重新运行 build.ps1 以更新 */")
$lines.Add("window.ASSET_DATA = window.ASSET_DATA || {};")

# 1) gif.worker.js(备用,单文件版无需;此处仍内嵌以保证多文件版可用)
$worker = [Convert]::ToBase64String([IO.File]::ReadAllBytes("$root\assets\vendor\gif.worker.js"))
$lines.Add("window.ASSET_DATA.worker = 'data:application/javascript;base64,$worker';")

# 2) 安洁莉娜素材
$lines.Add("window.ASSET_DATA.angelina = {};")
$cnMap = @{
  "zuozuo"   = "坐坐"; "paizhao" = "拍照"; "tanxian" = "探险"; "haibian" = "海边"
  "qianshui" = "潜水"; "kanshu"  = "看书"; "zhifeiji" = "纸飞机"; "gouwu" = "购物"
  "songhuo"  = "送货"; "qixing"  = "骑行"
}
Get-ChildItem "$root\assets\angelina\*.gif" | Sort-Object Name | ForEach-Object {
  $key = $_.BaseName
  $gif = [Convert]::ToBase64String([IO.File]::ReadAllBytes($_.FullName))
  $pngPath = "$root\assets\angelina\$key.png"
  if (-not (Test-Path -LiteralPath $pngPath)) { throw "缺少对应的静态图: $pngPath" }
  $png = [Convert]::ToBase64String([IO.File]::ReadAllBytes($pngPath))
  $display = if ($cnMap.ContainsKey($key)) { $cnMap[$key] } else { $key }
  $lines.Add("window.ASSET_DATA.angelina['$key'] = {name:'$display', gif:'data:image/gif;base64,$gif', png:'data:image/png;base64,$png'};")
}

# 3) UI 素材
$lines.Add("window.ASSET_DATA.ui = {};")
Get-ChildItem "$root\assets\ui\*.png" | Sort-Object Name | ForEach-Object {
  $b64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($_.FullName))
  $lines.Add("window.ASSET_DATA.ui['$($_.Name)'] = 'data:image/png;base64,$b64';")
}

[IO.File]::WriteAllLines("$root\assets-data.js", $lines)
$size = (Get-Item "$root\assets-data.js").Length
Write-Output "OK: assets-data.js generated ($([math]::Round($size/1MB,1)) MB)"

# 4) 生成单文件版 index-standalone.html(素材与依赖全部内嵌,一个文件即可使用/部署)
$html = [IO.File]::ReadAllText("$root\index.html")
$dataJs = [IO.File]::ReadAllText("$root\assets-data.js")
$gifJs  = [IO.File]::ReadAllText("$root\assets\vendor\gif.js")
$gifuct = [IO.File]::ReadAllText("$root\assets\vendor\gifuct.bundle.js")
$html = $html.Replace('<script src="assets-data.js"></script>', "<script>`n$dataJs`n</script>")
$html = $html.Replace('<script src="assets/vendor/gif.js"></script>', "<script>`n$gifJs`n</script>")
$html = $html.Replace('<script src="assets/vendor/gifuct.bundle.js"></script>', "<script>`n$gifuct`n</script>")
[IO.File]::WriteAllText("$root\index-standalone.html", $html, [System.Text.UTF8Encoding]::new($false))
$sSize = (Get-Item "$root\index-standalone.html").Length
Write-Output "OK: index-standalone.html generated ($([math]::Round($sSize/1MB,1)) MB)"
